### PR TITLE
added DisplayRecords.feature

### PR DESCRIPTION
**Pull request by devfrango**
Added key-value pair to configuration.properties, added DashboardPage, UserManagementPage, DisplayRecordsStepDefinitions, and DisplayRecordsFeature

### CODE REVIEW

**Review by huseyin9799 — APPROVED** [review]
Wow that UserManagement page has everything. Not sure if we need getters for every element but it might come in handy. Nice!

**Review by ghost — APPROVED** [review]
nice Frank

**Comment by devfrango** [comment]
> Wow that UserManagement page has everything. Not sure if we need getters for every element but it might come in handy. Nice!

You are right, Huseyin. I used this page to practice finding elements and making getters and setters. I will try to refactor it when I am fully awake.

**Comment by devfrango** [comment]
> nice Frank

Thank you, Abzal. I need to refactor it, but I couldn't stay awake any longer.

**Pull request merged**
